# Generated by Django 2.2 on 2019-05-22 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190518_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dp')),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 17, 54, 42, 569593)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 17, 54, 42, 568611)),
        ),
    ]
