# Generated by Django 2.2 on 2019-05-23 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190522_1754'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image_model',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 7, 30, 32, 360585)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 7, 30, 32, 359584)),
        ),
    ]
