# Generated by Django 2.2 on 2019-05-28 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190523_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 13, 12, 9, 151793)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_body',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 13, 12, 9, 150792)),
        ),
    ]
