# Generated by Django 2.2 on 2019-05-28 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190528_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 13, 33, 6, 220117)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 13, 33, 6, 220117)),
        ),
    ]
