# Generated by Django 2.2 on 2019-05-28 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190528_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_type',
            field=models.CharField(choices=[('T', 'Text Post'), ('M', 'Media Post'), ('U', 'URL Post')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 14, 19, 48, 391597)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_body',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 14, 19, 48, 390598)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_url',
            field=models.URLField(default=None, null=True),
        ),
    ]
