# Generated by Django 2.2 on 2019-06-01 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190601_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 9, 33, 27, 857770)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 1, 9, 33, 27, 856768)),
        ),
        migrations.AlterField(
            model_name='user_request',
            name='token',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
